spring.application.name=reportandbeheard

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/BDReportAndBeHeard
spring.datasource.username=postgres
spring.datasource.password=root
server.port=8084

jwt.secret=${JWT_SECRET:CAMBIA_ESTE_SECRETO_LOCALMENTE_NO_SUBIR_A_GIT}
